# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: Ubuntu-16.04

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path -y
      source $HOME/.cargo/env
      rustup component add clippy

      cargo --version
      cargo clippy --version
      rustc --version

      ./script/cibuild
    displayName: Build, lint, test

