[package]
name = "lithium"
version = "0.1.0"
authors = ["Lorenzo Villani <lorenzo@villani.me>"]
edition = "2018"

[dependencies]
jsonrpc-core = "14"
languageserver-types = "0.54"
serde = "1"
serde_json = "1"
url = "1"

[dev-dependencies]
pretty_assertions = "0.6"
